import { Rubik } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar';

const rubik = Rubik({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rubik',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${rubik.variable} scroll-smooth`}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
